### ISSUE TITLE
Block code

### ISSUE THREAD

**Issue by Snuffy4** [liyanboy74/soft-uart#3]
Hello, help me please. I use STM32F103C8T6 blue pill, i configured timer and soft uart. I'm trying send message, but it isn't work, for example, after HAL_TIM_Base_Start_IT(&htim3); the code is not executed

**Comment by liyanboy74** [comment]
See [Example](https://github.com/liyanboy74/soft-uart/tree/master/example) , it works fine for Blue Pill !

**Comment by meer-ul-husnain** [comment]
I am using the SoftUART library on an STM32F401 (Black Pill board) to read data from a NAMUR encoder.
The encoder communicates at 300 baud, even parity, 8 data bits, 1 stop bit.

When I run the code, the received data is corrupted:

Sometimes the buffer shows <NUL> characters.

Sometimes nothing is received at all.

It looks like the issue is related to buffer handling. The SoftUART RX buffer seems to block or overwrite data instead of working as a proper non-blocking, double-buffer (ping-pong) system.
